--liquibase formatted sql
--changeset tsoyka:1 runOnChange:true
drop table if exists client;
create table client(
    client_id int generated by default as identity,
    number char(11) not null unique
);